# Generated by Django 5.2.16 on 2026-07-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bidding", "0001_initial"),
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("bidding_open", "Bidding open"),
                            ("bid_received", "Bid received"),
                            ("bid_updated", "Bid updated"),
                            ("bid_counter", "Counter offer"),
                            ("counter_accepted", "Counter accepted"),
                            ("counter_declined", "Counter declined"),
                            ("bid_awarded", "Bid awarded"),
                            ("bid_lost", "Bid not selected"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("link_path", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=120)),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bidding.bid",
                    ),
                ),
                (
                    "bid_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="bidding.bidrequest",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="deliveries.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
