# Generated by Django 5.2.16 on 2026-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("pickup_location", models.CharField(max_length=255)),
                ("delivery_location", models.CharField(max_length=255)),
                ("pickup_datetime", models.DateTimeField()),
                ("delivery_window", models.CharField(blank=True, max_length=100)),
                ("package_details", models.CharField(max_length=255)),
                ("special_instructions", models.TextField(blank=True)),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                (
                    "request_source",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("dispatcher", "Dispatcher"),
                            ("admin", "Admin"),
                        ],
                        default="customer",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_assignment", "Pending Assignment"),
                            ("pending_driver_response", "Pending Driver Response"),
                            ("assigned", "Assigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_assignment",
                        max_length=40,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "package_weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("estimated_drive_minutes", models.PositiveIntegerField(default=0)),
                (
                    "fare",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("route_geometry", models.JSONField(blank=True, null=True)),
                (
                    "requested_vehicle_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("mixed", "Mixed distance + time"),
                            ("distance", "Distance only"),
                            ("time", "Time only"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                ("latest_note", models.CharField(blank=True, max_length=255)),
                ("decline_reason", models.CharField(blank=True, max_length=255)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("assigned", "Assigned"),
                            ("reassigned", "Reassigned"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("reached_pickup", "Reached Pickup"),
                            ("started", "Started"),
                            ("delivered", "Delivered"),
                            ("note", "Note"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
