# Generated by Django 5.2.16 on 2026-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FareSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(decimal_places=2, default=50, max_digits=10),
                ),
                (
                    "km_reference",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=10),
                ),
                (
                    "kg_base",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
                (
                    "kg_reference",
                    models.DecimalField(decimal_places=2, default=200, max_digits=10),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(decimal_places=2, default=10, max_digits=10),
                ),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "bidding_radius_km",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Fare settings",
            },
        ),
    ]
