# Generated by Django 5.2.16 on 2026-07-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("bidding", models.BooleanField(default=False)),
                (
                    "base_fare",
                    models.DecimalField(decimal_places=2, default=50, max_digits=10),
                ),
                (
                    "km_reference",
                    models.DecimalField(decimal_places=2, default=100, max_digits=10),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(decimal_places=2, default=15, max_digits=10),
                ),
                (
                    "kg_base",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=10),
                ),
                (
                    "kg_reference",
                    models.DecimalField(decimal_places=2, default=200, max_digits=10),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(decimal_places=2, default=5, max_digits=10),
                ),
                (
                    "per_minute_rate",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "bidding_radius_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vehicle Category",
                "verbose_name_plural": "Vehicle Categories",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=50, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("dry_van", "Dry Van"),
                            ("reefer", "Reefer"),
                            ("box_truck", "Box Truck"),
                            ("flatbed", "Flatbed"),
                            ("sprinter", "Sprinter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("gasoline", "Gasoline"),
                            ("electric", "Electric"),
                        ],
                        default="diesel",
                        max_length=20,
                    ),
                ),
                ("license_plate", models.CharField(max_length=50, unique=True)),
                ("image", models.TextField(blank=True)),
                ("bolo_number", models.CharField(blank=True, max_length=100)),
                ("last_service_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("offline", "Offline"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("fuel_level", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_driver",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vehicle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="vehicles.vehiclecategory",
                    ),
                ),
            ],
        ),
    ]
