# Generated by Django 5.2.16 on 2026-07-27 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bidding", "0001_initial"),
        ("deliveries", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidnegotiation",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_negotiations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidnegotiation",
            name="bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="bidding.bid",
            ),
        ),
        migrations.AddField(
            model_name="bidrequest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bid_requests",
                to="vehicles.vehiclecategory",
            ),
        ),
        migrations.AddField(
            model_name="bidrequest",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidrequest",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid_requests",
                to="deliveries.delivery",
            ),
        ),
        migrations.AddField(
            model_name="bidrequest",
            name="eligible_drivers",
            field=models.ManyToManyField(
                blank=True,
                related_name="eligible_bid_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidrequest",
            name="winning_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_bid_requests",
                to="bidding.bid",
            ),
        ),
        migrations.AddField(
            model_name="bidnegotiation",
            name="bid_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiations",
                to="bidding.bidrequest",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="bidding.bidrequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.UniqueConstraint(
                fields=("bid_request", "driver"), name="unique_bid_per_driver_request"
            ),
        ),
    ]
